development: &development

  #Application
  domain:              "http://localhost:3000"
  host:                "localhost:3000"
  facebook_page_token: "123123123|abcabcabc"

test:
  <<: *development

production:

  #Application
  domain:              "http://localhost:3000"
  host:                "localhost:3000"
  facebook_page_token: "123123123|abcabcabc"
