development: &development

  facebook_page_id:    "231320383554518"
  facebook_page_token: "123123123abcabcabc"

test:

  facebook_page_id:    "231320383554518"
  facebook_page_token: "123123123abcabcabc"

production:

  facebook_page_id:    "231320383554518"
  facebook_page_token: "123123123abcabcabc"
